/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane_otomasyonu;


import java.util.Map;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class hastarandevu extends javax.swing.JFrame {
int i,a;
static String j;
    /**
     * Creates new form hastarandevu
     */
    public hastarandevu() {
        initComponents();
       //JLabel ad=new JLabel(hashmap.b);
       //rpanel.add(ad);
       String d=doktorno.getText();
       String t=tarih.getText();
        dpanel.setLayout(new javax.swing.BoxLayout(dpanel, javax.swing.BoxLayout.LINE_AXIS));
        rpanel.setLayout(new javax.swing.BoxLayout(rpanel, javax.swing.BoxLayout.LINE_AXIS));
        
        for(i=0;i<hashmap.doktor.size()+1;i++){
         for(Map.Entry<String,String> entry:hashmap.doktor.entrySet()){
             
           JLabel p=new JLabel(entry.getValue());
           j=Integer.toString(i);
          
           JLabel j=new JLabel(p.getText());
           JLabel e=new JLabel(entry.getKey()+" no' lu doktor: ");
           JLabel b=new JLabel("   ");
           dpanel.add(e);
           dpanel.add(j);
           dpanel.add(b);
           
              }
          break;
       }
        
      if(hashmap.onayhasta.containsKey(hashmap.b)){
        
            for(a=0;a<hashmap.onaylanmıs.size()+1;a++){
            for(Map.Entry<String,String> entry:hashmap.onaylanmıs.entrySet()){
                JLabel x=new JLabel(entry.getValue());
                j=Integer.toString(a);
                JLabel j=new JLabel(x.getText());
                JLabel r=new JLabel(entry.getKey()+"no'lu doktorla randevu tarihiniz: " );
                JLabel b=new JLabel("   ");
                rpanel.add(r);
                rpanel.add(j);
                rpanel.add(b);
            }
            break;
}
    }
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tarih = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        onayg = new javax.swing.JButton();
        rpanel = new javax.swing.JPanel();
        temelor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doktorno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dpanel = new javax.swing.JPanel();
        temeld = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Randevu tarihi (gg/aa/yyyy) :");

        jLabel3.setText("Doktorlar:");

        onayg.setText("Onaya Gönder");
        onayg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaygActionPerformed(evt);
            }
        });

        rpanel.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout rpanelLayout = new javax.swing.GroupLayout(rpanel);
        rpanel.setLayout(rpanelLayout);
        rpanelLayout.setHorizontalGroup(
            rpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(temelor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rpanelLayout.setVerticalGroup(
            rpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rpanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(temelor)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel4.setText("Onaylanmış Randevularım:");

        doktorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktornoActionPerformed(evt);
            }
        });

        jLabel5.setText("Doktor No:");

        dpanel.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout dpanelLayout = new javax.swing.GroupLayout(dpanel);
        dpanel.setLayout(dpanelLayout);
        dpanelLayout.setHorizontalGroup(
            dpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(temeld)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dpanelLayout.setVerticalGroup(
            dpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(temeld)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(rpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(doktorno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(onayg)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onayg)
                    .addComponent(doktorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(dpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       hastaframe hf=new hastaframe();
       hf.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onaygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaygActionPerformed
       String d=doktorno.getText();
       String t=tarih.getText();
       if(hashmap.signpanelpersonel.containsKey(d)){
           hashmap.onay.put(d,t);
           hashmap.onayhasta.put(hashmap.b,d);
          
       }
    }//GEN-LAST:event_onaygActionPerformed

    private void doktornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hastarandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hastarandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hastarandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hastarandevu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hastarandevu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doktorno;
    public static javax.swing.JPanel dpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton onayg;
    private javax.swing.JPanel rpanel;
    private javax.swing.JTextField tarih;
    private javax.swing.JLabel temeld;
    private javax.swing.JLabel temelor;
    // End of variables declaration//GEN-END:variables

    
}
