package hastane_otomasyonu;

import static hastane_otomasyonu.hashmap.hAD;
import static hastane_otomasyonu.hashmap.hastaTC;
import static hastane_otomasyonu.hashmap.hsifre;
import static hastane_otomasyonu.hashmap.pAD;
import static hastane_otomasyonu.hashmap.personelNO;
import static hastane_otomasyonu.hashmap.psifre;
import static hastane_otomasyonu.hashmap.punvan;
import static hastane_otomasyonu.hashmap.signpanelhasta;
import static hastane_otomasyonu.hashmap.signpanelhastaad;
import static hastane_otomasyonu.hashmap.signpanelpersonel;
import static hastane_otomasyonu.hashmap.signpanelpersonelad;
import static hastane_otomasyonu.hashmap.signpanelpersonelunvan;
import static hastane_otomasyonu.hashmap.signpanelyonetici;
import static hastane_otomasyonu.hashmap.signpanelyoneticiad;
import static hastane_otomasyonu.hashmap.yAD;
import static hastane_otomasyonu.hashmap.yoneticiNO;
import java.util.HashMap;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class signin extends javax.swing.JFrame{
    
   
   
    public signin() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userpane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hastatc = new javax.swing.JTextField();
        hastasifre = new javax.swing.JPasswordField();
        hastagirisbutton = new javax.swing.JButton();
        hastaad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        personelno = new javax.swing.JTextField();
        personelsifre = new javax.swing.JPasswordField();
        personelgirisbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        personelad = new javax.swing.JTextField();
        doktoru = new javax.swing.JCheckBox();
        hemsireu = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yoneticino = new javax.swing.JTextField();
        yoneticisifre = new javax.swing.JPasswordField();
        yoneticigirisbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        yoneticiad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastane_otomasyonu/hastaneee.png"))); // NOI18N
        jLabel1.setOpaque(true);

        userpane.setBackground(new java.awt.Color(153, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setText("TC no:");

        jLabel3.setText("Şifre:");

        hastagirisbutton.setText("kaydol");
        hastagirisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastagirisbuttonActionPerformed(evt);
            }
        });

        hastaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaadActionPerformed(evt);
            }
        });

        jLabel8.setText("Ad-Soyad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(hastaad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hastasifre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(hastatc)
                    .addComponent(hastagirisbutton))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hastatc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hastasifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hastaad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hastagirisbutton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        userpane.addTab("HASTA KAYIT", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Personel No:");

        jLabel5.setText("Şifre:");

        personelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelnoActionPerformed(evt);
            }
        });

        personelgirisbutton.setText("kaydol");
        personelgirisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelgirisbuttonActionPerformed(evt);
            }
        });

        jLabel9.setText("Ad-Soyad:");

        doktoru.setText("doktor");
        doktoru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doktoruMouseClicked(evt);
            }
        });
        doktoru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktoruActionPerformed(evt);
            }
        });

        hemsireu.setText("hemşire");
        hemsireu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hemsireuMouseClicked(evt);
            }
        });
        hemsireu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemsireuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(personelad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personelsifre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(personelno)
                    .addComponent(personelgirisbutton))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doktoru)
                    .addComponent(hemsireu))
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(personelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(doktoru))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personelsifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personelad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hemsireu))
                .addGap(18, 18, 18)
                .addComponent(personelgirisbutton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        userpane.addTab("SAĞLIK PERSONELİ KAYIT", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Yönetici No:");

        jLabel7.setText("Şifre:");

        yoneticigirisbutton.setText("kaydol");
        yoneticigirisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigirisbuttonActionPerformed(evt);
            }
        });

        jLabel10.setText("Ad-Soyad:");

        yoneticiad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(yoneticiad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yoneticino, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(yoneticisifre)
                    .addComponent(yoneticigirisbutton))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yoneticino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(yoneticisifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticiad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(yoneticigirisbutton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        userpane.addTab("YÖNETİCİ KAYIT", jPanel4);

        jButton1.setText("geri");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(userpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userpane, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelnoActionPerformed
      
    }//GEN-LAST:event_personelnoActionPerformed

    private void hastagirisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastagirisbuttonActionPerformed
        hashmap.hastaTC= hastatc.getText();
        hashmap.hsifre=hastasifre.getText();
        hashmap.hAD=hastaad.getText();
        signpanelhastaad.put(hastaTC, hAD);
        signpanelhasta.put(hastaTC, hsifre);
        giris x= new giris();
        x.setVisible(true);
        setDefaultCloseOperation(signin.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_hastagirisbuttonActionPerformed

    private void yoneticigirisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigirisbuttonActionPerformed
        hashmap.yoneticiNO=yoneticino.getText();
        hashmap.ysifre=yoneticisifre.getText();
        hashmap.yAD=yoneticiad.getText();
        signpanelyoneticiad.put(yoneticiNO, yAD);
        signpanelyonetici.put(hashmap.yoneticiNO, hashmap.ysifre);
        giris x= new giris();
        x.setVisible(true);
        signin s=new signin();
        setDefaultCloseOperation(s.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_yoneticigirisbuttonActionPerformed

    private void personelgirisbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelgirisbuttonActionPerformed
      hashmap.personelNO=personelno.getText();
      hashmap.psifre=personelsifre.getText();
      hashmap.pAD=personelad.getText();
      signpanelpersonelad.put(personelNO, pAD);
      signpanelpersonel.put(personelNO, psifre);
      if(doktoru.isSelected()){
           signpanelpersonelunvan.put(hashmap.personelNO,"doktor");
           hashmap.doktor.put(personelNO,pAD);
      }
      else if(hemsireu.isSelected()){
           signpanelpersonelunvan.put(hashmap.personelNO,"hemşire");
           hashmap.hemsire.put(hashmap.personelNO,pAD);
      }
      giris x= new giris();
      x.setVisible(true);
      setDefaultCloseOperation(signin.EXIT_ON_CLOSE);
      dispose();
    }//GEN-LAST:event_personelgirisbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        LoginGui l=new LoginGui();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void hastaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaadActionPerformed

    private void yoneticiadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yoneticiadActionPerformed

    private void doktoruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktoruActionPerformed
      
    }//GEN-LAST:event_doktoruActionPerformed

    private void hemsireuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemsireuActionPerformed
       
    }//GEN-LAST:event_hemsireuActionPerformed

    private void doktoruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doktoruMouseClicked
     
      
    }//GEN-LAST:event_doktoruMouseClicked

    private void hemsireuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hemsireuMouseClicked
       
      
    }//GEN-LAST:event_hemsireuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox doktoru;
    private javax.swing.JTextField hastaad;
    private javax.swing.JButton hastagirisbutton;
    private javax.swing.JPasswordField hastasifre;
    private javax.swing.JTextField hastatc;
    private javax.swing.JCheckBox hemsireu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField personelad;
    private javax.swing.JButton personelgirisbutton;
    private javax.swing.JTextField personelno;
    private javax.swing.JPasswordField personelsifre;
    private javax.swing.JTabbedPane userpane;
    private javax.swing.JTextField yoneticiad;
    private javax.swing.JButton yoneticigirisbutton;
    private javax.swing.JTextField yoneticino;
    private javax.swing.JPasswordField yoneticisifre;
    // End of variables declaration//GEN-END:variables

    
}
