/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hastane_otomasyonu;


import static hastane_otomasyonu.hashmap.signpanelpersonel;


import java.util.Map;


import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class Yoneticiframe extends javax.swing.JFrame {
static String j;
int i;
static String x;
    /**
     * Creates new form Yoneticiframe
     */
    public Yoneticiframe() {
        initComponents();
        x=para.getText();
        
       /*for(Map.Entry<String,String> entry:hashmap.signpanelpersonelad.entrySet()){
          JLabel p=new JLabel(entry.getValue());
          personels.setText(p.getText()); 
       }*/
       
        for(i=0;i<signpanelpersonel.size()/2+1;i++){
         for(Map.Entry<String,String> entry:hashmap.signpanelpersonelad.entrySet()){
             
           JLabel p=new JLabel(entry.getValue());
           j=Integer.toString(i);
          
           JLabel j=new JLabel(p.getText());
           JLabel e=new JLabel(entry.getKey()+" no' lu personel: \n");
           JLabel b=new JLabel("   ");
           personelp.add(e);
           personelp.add(j);
           personelp.add(b);
           
              }
          break;
       }
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        para = new javax.swing.JTextField();
        maas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        personelp = new javax.swing.JPanel();
        arabutton = new javax.swing.JButton();
        unvanlabel = new javax.swing.JLabel();
        pnolabel = new javax.swing.JLabel();
        maaslabel = new javax.swing.JLabel();
        eklebutton = new javax.swing.JButton();
        maasg = new javax.swing.JLabel();
        adg = new javax.swing.JLabel();
        unvang = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Personel No:");

        para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraActionPerformed(evt);
            }
        });

        maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maasActionPerformed(evt);
            }
        });
        maas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maasKeyPressed(evt);
            }
        });

        jLabel2.setText("Maaş:");

        jLabel3.setText("Personel Ad: ");

        jLabel4.setText("Unvan:");

        jLabel5.setText("Personeller:");

        jButton1.setText("geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        personelp.setBackground(new java.awt.Color(153, 255, 153));
        personelp.setLayout(new javax.swing.BoxLayout(personelp, javax.swing.BoxLayout.LINE_AXIS));

        arabutton.setText("ara");
        arabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arabuttonMouseClicked(evt);
            }
        });
        arabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabuttonActionPerformed(evt);
            }
        });

        eklebutton.setText("ekle");
        eklebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebuttonActionPerformed(evt);
            }
        });

        jLabel9.setText("Maaş:");

        jLabel6.setText("Bütün işlemlerinizi enter tuşuna basarak kaydediniz.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maaslabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(maasg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(adg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(unvang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGap(57, 57, 57)
                                        .addComponent(pnolabel))
                                    .addComponent(arabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(eklebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(unvanlabel))
                                    .addComponent(jLabel9)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(para, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(arabutton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eklebutton)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unvanlabel)
                            .addComponent(pnolabel)
                            .addComponent(maaslabel)
                            .addComponent(maasg))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(adg)
                                .addGap(25, 25, 25)
                                .addComponent(unvang))
                            .addComponent(maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(personelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraActionPerformed
    x=para.getText();        
        
    }//GEN-LAST:event_paraActionPerformed

    private void maasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasActionPerformed
      
       
    }//GEN-LAST:event_maasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        giris g=new giris();
        g.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maasKeyPressed
       
        
    }//GEN-LAST:event_maasKeyPressed

    private void arabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabuttonActionPerformed
        if(signpanelpersonel.containsKey(x)){
            maasg.setText((String) hashmap.maas.get(x));
            unvang.setText(hashmap.signpanelpersonelunvan.get(x));
            adg.setText(hashmap.signpanelpersonelad.get(x));
        }
    }//GEN-LAST:event_arabuttonActionPerformed

    private void eklebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebuttonActionPerformed
       if(signpanelpersonel.containsKey(x)){
            String m=maas.getText();
           if(hashmap.maas.containsValue(m) && hashmap.maas.containsKey(x)){
               hashmap.maas.remove(x);
               hashmap.maas.put(x, m);
           }
           else{
               hashmap.maas.put(x, m);
           }
           
       }
           
           
    }//GEN-LAST:event_eklebuttonActionPerformed

    private void arabuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arabuttonMouseClicked
       if(signpanelpersonel.containsKey(x)){
            maasg.setText((String) hashmap.maas.get(x));
            unvang.setText(hashmap.signpanelpersonelunvan.get(x));
            adg.setText(hashmap.signpanelpersonelad.get(x));
        }
    }//GEN-LAST:event_arabuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yoneticiframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yoneticiframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yoneticiframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yoneticiframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yoneticiframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adg;
    private javax.swing.JButton arabutton;
    private javax.swing.JButton eklebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maas;
    private javax.swing.JLabel maasg;
    private javax.swing.JLabel maaslabel;
    private javax.swing.JTextField para;
    private javax.swing.JPanel personelp;
    private javax.swing.JLabel pnolabel;
    private javax.swing.JLabel unvang;
    private javax.swing.JLabel unvanlabel;
    // End of variables declaration//GEN-END:variables
}
